### ISSUE TITLE
QAWolf having trouble finding a similar element twice

### ISSUE THREAD

**Issue by arggh** [qawolf/qawolf#550] opened 2020-04-05 13:35 UTC
I'm bumping into test run errors where QAWolf can't find the element it's supposed to be interacting with. What makes it even stranger, there's a recurring pattern where QAWolf finds the same element on the first interaction, but when I try to access an identical element right after that, it's not found and the test timeouts.

This can be seen for example when interacting with a list, where each item has the same actions.

### Flow of things

1. Open list item 1 dialog
2. Toggle checkbox in the opened dialog
3. Close dialog
4. Open list item 2 dialog
5. Toggle checkbox in the opened dialog → **element not found, test timeouts**

The selectors in both cases are equal, but the element is just not found the second time.

**Comment by flaurida** [comment] 2020-04-05 15:02
Hi @arggh - once again thank you for reporting this issue :)

In order for me to repro, it would help if I have more context about the specific UI elements in play. That way I can diagnose the root cause of this issue. Could you share which UI library you are using, or link to some sort of site or sandbox? If I have the HTML of the elements I can create a repro and get to the bottom of why there isn't a match.

Please let me know if this is possible, thanks!

**Comment by arggh** [comment] 2020-04-05 17:25
This occurred when the script was trying to toggle an input of type checkbox, placed inside an absolutely positioned popover element, which had an entry animation.

The test succesfully opens the popover and toggles the checkbox, but an immediately following attempt to open the same popover (but related to another item on the list) and toggle the same checkbox - fails.

The code that causes this behavior is sadly not open source, so I can't just point you at it. I did, however, try to build a repro.

I extracted the checkbox component, thinking it might be due to the CSS trickery required to style a checkbox component, but turns out that's not the case. I then tried to apply the same kind of popover element to wrap the checkboxes, but no luck there either.

Here's the failing selector, if that's of any help:

```
"html=<div class=\"left--a3123a391 field--bc37d4ed3\" qaw_innertext=\"Pay in parts\"><div class=\"checkboxWrapper--1ce388929 medium--c7589ac47\" qaw_innertext=\"Pay in parts\"><input type=\"checkbox\" id=\"checkbox_tYA\" class=\"checkbox--cb8009ecf\" qaw_labels=\"Pay in parts\" /></div></div>"
```

Here's the corresponding HTML:

```
<div class="left--a3123a391 field--bc37d4ed3">
  <div class="checkboxWrapper--1ce388929 medium--c7589ac47">
    <div class="rectangle--3d2969973">
      <svg class="svg--d73f3dcfe" viewBox="0 0 100 100">
      </svg>
    </div>
    <input type="checkbox" id="checkbox_MsB" class="checkbox--cb8009ecf">
    <label for="checkbox_MsB" class="label--2a4bb0cb5">Pay in parts</label>
  </div>
</div>
```

As you might notice, the `id`-attribute of the checkbox is different compared to the selector. At first I thought that might be the cause, since those are randomly generated, but setting them to fixed values didn't solve the problem.

I understand this might not help at all. I'll see if I can extract a usable repro.

**Comment by flaurida** [comment] 2020-04-05 18:08
Thanks so much for this!

I'll try to create a repro with this within the next day and see how it goes. Specifically, I'll try to have two of these checkboxes on the page to see if it times out. 

Not sure if this is helpful, but as a temporary workaround you can always replace the default selectors with a CSS or text selector. I'll definitely look into this, but wanted to give you an option to help get your test working in the meantime.

```js
await page.click(".some-class"); // CSS selector
await page.click("text='my text'"); // text selector
```

**Comment by flaurida** [comment] 2020-04-05 20:55
While investigating this, I encountered the following error. Is this also the error you are seeing @arggh ? I'll share a repro repo shortly.

```
TimeoutError: waiting for selector "undefined" failed: timeout 30000ms exceeded
```

**Comment by flaurida** [comment] 2020-04-05 21:24
Here is a repo that tries to repro the HTML you described: https://github.com/flaurida/checkbox-test. If you'd like to run it yourself, please clone it and run `npm install` followed by `npm run start`.

In short, when I recorded a test with the steps you provided, it worked for me. I made sure to make the ids and classes dynamic as well. 

1. Open list item 1 dialog
2. Toggle checkbox in the opened dialog
3. Close dialog
4. Open list item 2 dialog
5. Toggle checkbox in the opened dialog 

However, there was a separate bug that I found ticketed here: #551. This bug occurred when the test referred to an undefined selector. If The error message is the same one as what you are seeing then that's probably the culprit. We are going to fix this bug soon.

Otherwise, we'll have to explore what the gaps are between my test repo and your codebase. Please keep me posted, and happy to hop on a call if that's easier. Thanks again for reporting this 😊

**Comment by arggh** [comment] 2020-04-06 06:45
The error I get is `Protocol error (Runtime.callFunctionOn): Target closed.`.

I inspected the components in question and the popover/dialog is somewhat poorly designed. It inserts a "click catcher" element, a div with `position: fixed` covering the entire screen, to the DOM. Coupled with a closing animation, I was 99% sure that was the culprit, I couldn't yet reproduce the problem in my repro.

However, I did notice that if I click a few other places before opening list item 2 dialog, the checkbox toggling works as expected. Also setting the transition & animation durations to 0 in this popover component fixes the test.

I'm pretty sure it's some sort of timing issue between the app code and the waiting logic of QAWolf/Playwright.

**Comment by arggh** [comment] 2020-04-06 08:22
I tried pretty hard to reproduce this outside of our app code, but so far no luck. I must be missing something.

However, after noticing this is most certainly a timing issue, I tried different values for the entry- and exit-animations of the popover.

10ms: test succeeds
70ms: test succeeds
100ms: `Evaluation failed: Error: Element is not attached to the DOM`
200ms+: `Protocol error (Runtime.callFunctionOn): Target closed.`

**Comment by arggh** [comment] 2020-04-06 10:24
Oh hey, I managed to build a repro.

Create two identical tests with the steps described below against these URL's and see what happens:

https://ecstatic-booth-c41be5.netlify.com/?duration=0
https://ecstatic-booth-c41be5.netlify.com/?duration=300

The query parameter `duration` determines the duration in milliseconds for popover entry- and exit-animations.

### Test steps

1. Click "Open Foo"
2. Toggle checkbox
3. Click "Close"
4. Click "Open Bar"
5. Toggle checkbox
6. Click "Close"

If it works for you the same, the test ran with `duration=0` will succeed, but the test ran with `duration=300` will fail.

### How

The key to replicating this was using the combination of entry- and exit-animations and dynamic id-attributes for the checkboxes.

### Why

When one studies the selectors, both in our app code and in the repro, they are identical for both checkboxes apart from the id-attributes, but those won't match anyway, since they're randomly generated.

Now, when QAWolf is trying to click the second checkbox, due to the exit-animation, QAWolf will find the first checkbox instead, which is about to get removed from DOM real soon, and try to toggle that.

I suppose QAWolf normally has a mechanism to make sure the correct element is targeted out of many identical ones by broadening the scope of the selector or introducing indexes, but since my mouse hand isn't as quick as QAWolf, by the time I'm clicking that second checkbox, only one matching element will be present in the DOM, thus fooling the wolf!

**Comment by flaurida** [comment] 2020-04-06 15:33
Hi @arggh - thank you for the detailed reproduction! 🐺 

This is a tricky case, and I'm trying to think through how QA Wolf should handle this. To give a bit more detail, if QA Wolf finds a "strong" match to the target element, it will click that one. One of the criteria for a strong match is a matching label. In this case, there are two elements with a matching label to the target element. In the event of a tie, it will choose the better match, though in this case it seems like the matches are equal given the dynamic ids/classes. Another complicating factor is that it sounds like only one of the elements may be visible on the page at the time anyway, depending on how fast the animation is.

At first blush, I would be inclined to add a call to [Playwright's `page.waitFor`](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitforselectororfunctionortimeout-options-arg) method to your test, passing it a function to check that the exit animation is complete. That way, QA Wolf won't start looking for the second checkbox until we know the first animation is done.

I'm open to other ideas for how QA Wolf should handle this as well, right now it's not clear to me. I'll keep thinking about it in the meantime.

**Comment by arggh** [comment] 2020-04-06 16:49
As a user of QAWolf (and therefore having an incomplete understanding of the subject), after the first failure due to the target being removed mid-operation, I would expect QAWolf to poll for the correct target element, instead of just idling for 30 seconds until timeout. That would be in line with the following statement on qawolf.com: 

> Your tests automatically wait for elements

**Comment by flaurida** [comment] 2020-04-06 17:14
Thanks @arggh - agree with you that it should not just timeout. Let me discuss with @jperl and get back to you about next steps. Appreciate all your help in improving QA Wolf 😊🐺

**Comment by flaurida** [comment] 2020-04-06 22:16
We are going to look into this first thing tomorrow, will keep you posted!

**Comment by flaurida** [comment] 2020-04-07 15:01
Hi @arggh  - just looked into this. I wanted to isolate where the issue was, and in this case it is with the Playwright `page.click` method. This test that is pure Playwright (no QA Wolf code/selectors) has the same issue:

```js
const { chromium } = require("playwright");

let browser;
let page;

beforeAll(async () => {
  browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  page = await context.newPage();
});

afterAll(async () => {
  await browser.close();
});

test("disappearingElement", async () => {
  await page.goto("https://ecstatic-booth-c41be5.netlify.com/?duration=300", {
    timeout: 60000,
  });

  await page.click("main > div:first-child button");
  await page.click("label");
  await page.click('text="Close"');
  await page.click("main > div:last-child button");
  await page.click("label");
  await page.click('text="Close"');
});
```

From looking at the Playwright source code, it seems that click 1) finds a matching element and 2) tries to click it. It does not then go back and try again if the first element is no longer on the page (at least from what I can tell). [I have filed an issue with Playwright](https://github.com/microsoft/playwright/issues/1691) and am waiting to hear back.

If possible, we would like this to be addressed in Playwright. We generate as close to pure Playwright code as possible because we think that provides a better developer experience than QA Wolf having custom `click`, etc. methods. 

We are sorry for the inconvenience this is causing you. Would it be possible to use the [`page.waitFor` workaround](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitforselectororfunctionortimeout-options-arg) for now, while we wait to hear back from Playwright? Once we have more information we can decide on next steps.

Once again, I appreciate your help in surfacing this issue. Please keep the feedback coming 🐺

**Comment by arggh** [comment] 2020-04-07 17:22
We had this solved on our end immediately when I figured out the reason it was failing, so no need to worry 😊

I'm glad if I can be of any help, I have vested interest in improving QA Wolf!

**Comment by flaurida** [comment] 2020-04-07 18:51
Hi @arggh appreciate it and glad you have a workaround for now :) I am also glad you found this bug 🐛, as I agree with you that just timing out does not seem like expected behavior.

I'll keep this issue open for now and update it as I get more information. We are finalizing our next release which should address at least some of the other issues you filed.

Thank you again for your time, and excited to keep improving QA Wolf with your input 🐺

**Comment by jperl** [comment] 2020-05-01 04:09
We revamped QA Wolf to use regular CSS and text selectors in the latest release. Feel free to re-open this ticket or a new one if you have issues with the latest QA Wolf.

**Closed by jperl** 2020-05-01 04:09 UTC
