### ISSUE TITLE
❗Test generation error

### ISSUE THREAD

**Issue by alexandrudanpop** [qawolf/qawolf#176] opened 2019-11-19 09:10 UTC
I had the following error when automatig a test case. What I tried to do was add a new item in a list table then edit that item, then delete it. 

  √ Recording browser actions
  × Saving "add_data_source" test
    → Cannot read property 'code' of undefined
{ TypeError: Cannot read property 'code' of undefined
    at keysToType.split.forEach.key (c:\_projects\UI.E2E.Tests\node_modules\@qawolf\browser\lib\keyboard.js:29:36)
    at Array.forEach (<anonymous>)
    at Object.exports.buildStrokesForString (c:\_projects\UI.E2E.Tests\node_modules\@qawolf\browser\lib\keyboard.js:25:26)
    at Object.exports.buildKeyEvents (c:\_projects\UI.E2E.Tests\node_modules\@qawolf\build-workflow\lib\replacePasteEvents.js:6:31)
    at Object.exports.replacePasteEvents (c:\_projects\UI.E2E.Tests\node_modules\@qawolf\build-workflow\lib\replacePasteEvents.js:49:43)
    at Object.exports.buildSteps (c:\_projects\UI.E2E.Tests\node_modules\@qawolf\build-workflow\lib\buildSteps.js:10:41)    at Object.exports.buildWorkflow (c:\_projects\UI.E2E.Tests\node_modules\@qawolf\build-workflow\lib\buildWorkflow.js:5:32)
    at c:\_projects\UI.E2E.Tests\node_modules\qawolf\node_modules\@qawolf\cli\lib\record.js:52:51
    at Generator.next (<anonymous>)
    at fulfilled (c:\_projects\UI.E2E.Tests\node_modules\qawolf\node_modules\@qawolf\cli\lib\record.js:5:58) context: [Object: null prototype] {} }

**Comment by alexandrudanpop** [comment] 2019-11-19 09:19
Looking closer at it I think the problem is dropdown selection. I use semantic UI dropdowns.

**Comment by jperl** [comment] 2019-11-19 15:40
I will look into this today. Thanks for reporting the issue

**Comment by jperl** [comment] 2019-11-19 17:43
@alexandrudanpop Based on looking at the error I believe a key you typed is not in puppeteer's [USKeyboardLayout](https://github.com/GoogleChrome/puppeteer/blob/master/lib/USKeyboardLayout.js).

I am looking into a workaround now, but is that possible?

**Comment by alexandrudanpop** [comment] 2019-11-20 09:05
That might be possible. I tried again to record a simpler test with a dropdown and the recording part worked now. 

But then running the tests failed:
2019-11-20T09:00:23.843Z error: retryExecutionError: will not retry unknown error: "No element handle found for step [object Object]"
 FAIL  .qawolf/tests/1.test.js (51.94s)
  ● 1 › can click "english - great britain" div

    No element handle found for step [object Object]

      at node_modules/@qawolf/browser/src/find.ts:38:11
      at fulfilled (node_modules/@qawolf/browser/lib/find.js:5:58)

---
I will try to publish a repro of the issues when I find some free time.

**Comment by jperl** [comment] 2019-11-20 13:48
Thanks I am adding multi-language support right now to fix the first issue. After that I will look into reproducing the second issue. 

Was the Great Britain div a semantic ui dropdown or a different type of element?

**Comment by alexandrudanpop** [comment] 2019-11-21 12:43
Yep it was a dropdown.

**Comment by jperl** [comment] 2019-11-21 16:11
Just released support for all keyboards to fix the test generation error you had before.

I am working on adding an example with semantic-ui dropdowns to investigate your second issue.

**Comment by jperl** [comment] 2019-11-22 15:24
@alexandrudanpop Was able to reproduce the issue on the search dropdown 👍. Working on a fix in #189

**Comment by jperl** [comment] 2019-11-22 16:16
The issue is two-fold

1) qawolf ignores clicks on inputs (we incorrectly assume you will type in an input)
2) qawolf does not click on any hidden elements, so the element never appears

A [workaround](https://github.com/qawolf/semanticui-example/blob/master/.qawolf/tests/search_dropdown.test.js) until I fix the behavior above is to type into the search dropdown.

![video](https://user-images.githubusercontent.com/1136652/69441810-5cc55080-0d19-11ea-9de5-f98d6c0c60a7.gif)

**Comment by jperl** [comment] 2019-11-22 17:34
The fix #196 for the search dropdown is fixed in [v0.5.14](https://www.npmjs.com/package/qawolf). 

It now [clicks](https://github.com/qawolf/semanticui-example/blob/master/.qawolf/tests/search_dropdown_click.test.js) on the input/opens the list correctly, but you will need to re-record the test.

![video](https://user-images.githubusercontent.com/1136652/69447053-ab77e800-0d23-11ea-89f3-48871d80b911.gif)

However if you want to reduce the number of test steps you can still [type](https://github.com/qawolf/semanticui-example/blob/master/.qawolf/tests/search_dropdown_type.test.js) and press Enter instead.

P.S. I am working on speeding up the matching logic right now in #189 so tests will run a lot faster shortly.

**Comment by jperl** [comment] 2019-11-22 17:35
Closing this since the fixes are merged, but please re-open if it does not resolve your issue.

**Closed by jperl** 2019-11-22 17:35 UTC
Labels: bug
